export const GUIDES = [
  {
    dir: 'what-is-a-qr-code',
    title: 'What Is a QR Code? | EverQR Guides',
    heading: 'What is a QR code?',
    description: 'A plain-language explanation of QR codes and how they store information.',
    content: `<p>A QR (Quick Response) code is a two-dimensional barcode that stores data as a pattern of modules. Phone cameras and scanners read the pattern and decode the information instantly.</p><p>Unlike one-dimensional barcodes, QR codes can hold URLs, text, contact cards, Wi‑Fi credentials, and more — which is why they’re used on packaging, posters, restaurants, and business cards.</p>`,
  },
  {
    dir: 'how-qr-codes-work',
    title: 'How QR Codes Work | EverQR Guides',
    heading: 'How QR codes work',
    description: 'Learn how scanners read QR modules, finder patterns, and error correction.',
    content: `<p>QR codes use finder patterns (the three large corner squares) so scanners can locate and orient the code quickly. Data is encoded into the remaining modules with error correction so damaged codes can still scan.</p><p>When you create a static QR with EverQR, the payload is written directly into those modules in your browser.</p>`,
  },
  {
    dir: 'static-vs-dynamic-qr-codes',
    title: 'Static vs Dynamic QR Codes | EverQR Guides',
    heading: 'Static vs dynamic QR codes',
    description: 'Understand the difference between static and dynamic QR codes.',
    content: `<p><strong>Static QR codes</strong> encode the final content directly. After you download them, they don’t need our servers. <strong>Dynamic QR codes</strong> usually point to a short redirect URL you can edit later — useful for campaigns, but dependent on a service remaining online.</p><p>EverQR v1 focuses on static QR codes: free, private, and permanent with respect to our infrastructure.</p>`,
  },
  {
    dir: 'do-qr-codes-expire',
    title: 'Do QR Codes Expire? | EverQR Guides',
    heading: 'Do QR codes expire?',
    description: 'Clear answer on QR expiration for static codes generated with EverQR.',
    content: `<p>Static QR codes generated here do not expire and do not depend on our servers. The encoded destination or information must remain valid for the QR code to remain useful — for example, a website must stay online, or a phone number must still ring.</p>`,
  },
  {
    dir: 'qr-code-error-correction',
    title: 'QR Code Error Correction Levels | EverQR Guides',
    heading: 'QR code error correction',
    description: 'Choose L, M, Q, or H error correction for logos and print durability.',
    content: `<p>Error correction lets scanners recover data if part of the QR is dirty, covered by a logo, or lightly damaged. Levels L, M, Q, and H trade capacity for resilience. Use <strong>H</strong> when adding a logo or printing small.</p>`,
  },
  {
    dir: 'qr-code-size-guide',
    title: 'QR Code Size Guide | EverQR Guides',
    heading: 'QR code size guide',
    description: 'Recommended QR sizes for print, packaging, posters, and screens.',
    content: `<p>As a rule of thumb, printed QR codes should be at least 2 × 2 cm (about 0.8 × 0.8 in) for short URLs, and larger for complex payloads or long scanning distances. Test with a real phone before a large print run.</p>`,
  },
  {
    dir: 'qr-code-printing-guide',
    title: 'QR Code Printing Guide | EverQR Guides',
    heading: 'QR code printing guide',
    description: 'Print QR codes that scan reliably — contrast, quiet zone, and materials.',
    content: `<p>Maintain strong contrast, keep the quiet zone (margin) clear, avoid distorting the code, and prefer matte finishes over heavy gloss glare. SVG downloads scale cleanly for professional print.</p>`,
  },
  {
    dir: 'qr-code-best-practices',
    title: 'QR Code Best Practices | EverQR Guides',
    heading: 'QR code best practices',
    description: 'Practical tips for designing QR codes people will actually scan.',
    content: `<p>Tell people what happens when they scan, place codes at comfortable heights, keep designs scannable, and test on multiple devices. Don’t bury critical CTAs behind a QR without a fallback URL when appropriate.</p>`,
  },
  {
    dir: 'qr-code-security',
    title: 'QR Code Security | EverQR Guides',
    heading: 'QR code security',
    description: 'Stay safe with QR codes — verify destinations and avoid risky scans.',
    content: `<p>QR codes are only as trustworthy as their content. Preview URLs when your device allows it, be cautious with unexpected codes in public places, and never encode secrets you wouldn’t print on paper.</p>`,
  },
  {
    dir: 'qr-code-for-business',
    title: 'QR Codes for Business | EverQR Guides',
    heading: 'QR codes for business',
    description: 'Business use cases for static QR codes — packaging, cards, and signage.',
    content: `<p>Businesses use QR codes for menus, product info, support links, Wi‑Fi, reviews, and contact cards. Static codes are ideal when the destination is stable and you want zero dependency on a QR vendor after printing.</p>`,
  },
  {
    dir: 'qr-code-for-restaurants',
    title: 'QR Codes for Restaurants | EverQR Guides',
    heading: 'QR codes for restaurants',
    description: 'Menus, Wi‑Fi, and review QR ideas for restaurants and cafes.',
    content: `<p>Restaurants commonly use QR codes for menus, Wi‑Fi access, and Google reviews. Keep table tents clean, high contrast, and easy to scan in low light.</p>`,
  },
  {
    dir: 'qr-code-for-wifi',
    title: 'Wi‑Fi QR Codes Guide | EverQR Guides',
    heading: 'QR codes for Wi‑Fi',
    description: 'How Wi‑Fi QR codes work and how to share guest access safely.',
    content: `<p>A Wi‑Fi QR encodes SSID, security type, and password in a standard format many phones understand. Prefer a guest network when sharing access publicly, and reprint if you rotate passwords.</p>`,
  },
  {
    dir: 'qr-code-for-google-reviews',
    title: 'Google Review QR Codes | EverQR Guides',
    heading: 'QR codes for Google reviews',
    description: 'Collect more Google reviews with a simple printable QR code.',
    content: `<p>Place a Google review QR at checkout, on receipts, or near exits. Make sure your Google Business link is correct, then generate a static QR so customers can leave feedback in seconds.</p>`,
  },
  {
    dir: 'qr-code-with-logo',
    title: 'QR Codes with Logos | EverQR Guides',
    heading: 'QR codes with logos',
    description: 'Add a logo without breaking scan reliability — ECC and size tips.',
    content: `<p>Logos should stay relatively small, keep high error correction (H), and preserve enough contrast. Always scan-test after adding branding.</p>`,
  },
];
