export const LEGAL_PAGES = [
  {
    slug: "about",
    file: "about.html",
    title: "About EverQR",
    description: "EverQR is a free, private, static QR code generator that runs in your browser.",
    heading: "About EverQR",
    content: "<p>EverQR helps anyone create free, permanent, private, unlimited static QR codes — no signup, no watermark, no expiration on our side.</p><p>We built the product around browser-side generation so your content doesn’t need to travel to our servers just to become a QR code.</p>",
  },
  {
    slug: "privacy-policy",
    file: "privacy-policy.html",
    title: "Privacy Policy | EverQR",
    description: "How EverQR handles privacy for client-side QR generation.",
    heading: "Privacy policy",
    content: "<p>EverQR is designed so normal static QR generation happens in your browser. We do not require an account, and we do not need your QR payloads on a server to create PNG, SVG, or JPG downloads.</p><p>LocalStorage and IndexedDB may store preferences and saved designs on your device only. If analytics are enabled in a future release, they must never include QR payload content.</p><p>Contact: hello@everqr.app</p>",
  },
  {
    slug: "terms",
    file: "terms.html",
    title: "Terms of Use | EverQR",
    description: "Terms for using the EverQR static QR code generator.",
    heading: "Terms of use",
    content: "<p>EverQR is provided free of charge for lawful use. You are responsible for the content you encode and for complying with applicable laws.</p><p>Static QR codes do not expire because of EverQR, but third-party destinations may change. The service is provided “as is” without warranties.</p>",
  },
  {
    slug: "disclaimer",
    file: "disclaimer.html",
    title: "Disclaimer | EverQR",
    description: "Important technical disclaimer about static QR permanence.",
    heading: "Disclaimer",
    content: "<p>Static QR codes generated here do not expire and do not depend on our servers. The encoded destination or information must remain valid for the QR code to remain useful.</p>",
  },
  {
    slug: "contact",
    file: "contact.html",
    title: "Contact | EverQR",
    description: "Contact EverQR support.",
    heading: "Contact",
    content: "<p>Email us at <a class=\"text-brand-800 underline\" href=\"mailto:hello@everqr.app\">hello@everqr.app</a>. We don’t require accounts, so include enough detail for us to help.</p>",
  },
  {
    slug: "faq",
    file: "faq.html",
    title: "FAQ | EverQR",
    description: "Frequently asked questions about EverQR static QR codes.",
    heading: "Frequently asked questions",
    content: "<p><strong>Is EverQR really free?</strong> Yes — unlimited static QR generation with no watermark.</p><p><strong>Do I need to sign up?</strong> No.</p><p><strong>Do QR codes expire?</strong> Static codes generated here do not expire and do not depend on our servers. External destinations must remain valid.</p>",
  },
  {
    slug: "accessibility",
    file: "accessibility.html",
    title: "Accessibility | EverQR",
    description: "EverQR accessibility commitments.",
    heading: "Accessibility",
    content: "<p>We aim for semantic HTML, keyboard access, visible focus, labeled forms, and sufficient contrast. If you hit a barrier, email hello@everqr.app.</p>",
  },
  {
    slug: "security",
    file: "security.html",
    title: "Security | EverQR",
    description: "Security practices for the EverQR client-side generator.",
    heading: "Security",
    content: "<p>We sanitize user-controlled text before HTML insertion, validate URLs and uploads, keep dependencies minimal, and avoid executing imported project JSON as code.</p>",
  },
  {
    slug: "changelog",
    file: "changelog.html",
    title: "Changelog | EverQR",
    description: "Product changelog for EverQR.",
    heading: "Changelog",
    content: "<p><strong>v1.0.0</strong> — Initial release with URL, Text, Wi‑Fi, WhatsApp, Google Review, vCard, Email, SMS, Phone, and Location generators; live preview; PNG/SVG/JPG export; local saved designs.</p>",
  },
  {
    slug: "offline",
    file: "offline.html",
    title: "Offline | EverQR",
    description: "You appear to be offline.",
    heading: "You are offline",
    content: "<p>Reconnect to load the latest assets. Saved designs already on this device may still be available when you return online.</p>",
  }
];
